### ISSUE TITLE
Previous/future work

### ISSUE THREAD

**Issue by teutzue** [Sindt/UFO#3]
Can you guys provide a thorough summary of your previous work and propose and discusse future work in detail?

**Comment by Sindt** [comment]
We discussed this together in the group, and we think that we allready provided the things you are asking. First of all, the "previous work" is described in the part: Hyper-V’s and the Blue Screen of Death!
We explains that we in the beginning are having some troubles with vagrant and docker running at the same time on windows, in depth.

After that we desribed the future work as well, be telling that now we found a solution on our problems, by running docker through the docker provider, and that's the way we will keep doing it in the future.
